/**
 * Top-level frontmatter field edits (task-045-memory-submit) — the line-based primitives the Memory
 * transition verbs use to change `status` and add/remove `rejection_reason`
 * (`spec-010-memory-frontmatter-schema` field-write ownership) without re-serializing the document.
 * A re-serialization would drop the templates' inline `# REQUIRED …` comments and reorder nothing
 * the verb owns — the same defect class as bug-004 for `dna set`. Every byte outside the edited
 * line(s) must survive.
 */
import { removeFrontmatterField, setFrontmatterField } from '../../src/memory/frontmatter-edit';

const DOC = `---
id: "task-101"         # auto-generated by wingfoil
type: task
title: "Ship it"       # REQUIRED — e.g. "Implement X"
status: draft          # auto-set by wingfoil
rejection_reason: "needs tests"
nested:
  status: keep-me
tags: []
---

## Description

status: this body line is not frontmatter
`;

describe('setFrontmatterField', () => {
  it('replaces a top-level value, keeping its trailing comment and every other byte', () => {
    const out = setFrontmatterField(DOC, 'status', 'pending');
    expect(out).toBe(DOC.replace('status: draft          # auto-set by wingfoil', 'status: pending          # auto-set by wingfoil'));
  });

  it('never touches a nested key of the same name, nor a body line that looks like one', () => {
    const out = setFrontmatterField(DOC, 'status', 'pending');
    expect(out).toContain('  status: keep-me');
    expect(out).toContain('status: this body line is not frontmatter');
  });

  it('replaces a quoted value whose content contains a `#`', () => {
    const doc = '---\ntitle: "a # b"   # c\n---\nbody\n';
    expect(setFrontmatterField(doc, 'title', '"x"')).toBe('---\ntitle: "x"   # c\n---\nbody\n');
  });

  it('appends the field at the end of the frontmatter when absent', () => {
    const doc = '---\nid: a\n---\nbody\n';
    expect(setFrontmatterField(doc, 'rejection_reason', '"why"')).toBe('---\nid: a\nrejection_reason: "why"\n---\nbody\n');
  });

  it('throws on a document without a frontmatter block', () => {
    expect(() => setFrontmatterField('no frontmatter', 'status', 'x')).toThrow('no frontmatter block');
  });
});

describe('removeFrontmatterField', () => {
  it('removes a top-level key line and leaves every other byte intact', () => {
    expect(removeFrontmatterField(DOC, 'rejection_reason')).toBe(DOC.replace('rejection_reason: "needs tests"\n', ''));
  });

  it('removes the indented continuation lines of a block value too', () => {
    const doc = '---\nid: a\nrejection_reason: |\n  line one\n  line two\ntags: []\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\nid: a\ntags: []\n---\nbody\n');
  });

  it('is a no-op (same string) when the key is absent', () => {
    const doc = '---\nid: a\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe(doc);
  });

  it('removes the last frontmatter line cleanly', () => {
    const doc = '---\nid: a\nrejection_reason: x\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\nid: a\n---\nbody\n');
  });
});
