/**
 * Top-level frontmatter field edits (task-045-memory-submit) — the line-based primitives the Memory
 * transition verbs use to change `status` and add/remove `rejection_reason`
 * (`spec-010-memory-frontmatter-schema` field-write ownership) without re-serializing the document.
 * Every byte outside the edited entry must survive, and the edited entry must be exactly the YAML
 * entry — a value's continuation lines included, a following comment that belongs to the parent
 * mapping excluded. The second pass (task-045 rejection, d7b9d70) adds the cases the first pass got
 * wrong: block scalars with blank lines, CRLF, an unspaced `#` in a plain value, multi-line values,
 * and YAML-safe serialization of arbitrary string values. Edits are also checked by re-parsing with
 * js-yaml, so a test cannot pass on bytes that look right but parse wrong.
 */
import { load } from 'js-yaml';

import { removeFrontmatterField, setFrontmatterField, verifyFrontmatterEdit } from '../../src/memory/frontmatter-edit';
import { splitFrontmatter } from '../../src/storage';

/** Parse a document's frontmatter the way every reader of Memory documents does. */
function parsed(content: string): Record<string, unknown> {
  return load(splitFrontmatter(content).frontmatter ?? '') as Record<string, unknown>;
}

const DOC = `---
id: "task-101"         # auto-generated by wingfoil
type: task
title: "Ship it"       # REQUIRED — e.g. "Implement X"
status: draft          # auto-set by wingfoil
rejection_reason: "needs tests"
nested:
  status: keep-me
tags: []
---

## Description

status: this body line is not frontmatter
`;

describe('setFrontmatterField', () => {
  it('replaces a top-level value, keeping its trailing comment and every other byte', () => {
    const out = setFrontmatterField(DOC, 'status', 'pending');
    expect(out).toBe(DOC.replace('status: draft          # auto-set by wingfoil', 'status: pending          # auto-set by wingfoil'));
  });

  it('never touches a nested key of the same name, nor a body line that looks like one', () => {
    const out = setFrontmatterField(DOC, 'status', 'pending');
    expect(out).toContain('  status: keep-me');
    expect(out).toContain('status: this body line is not frontmatter');
    expect(parsed(out).nested).toEqual({ status: 'keep-me' });
  });

  it('replaces a quoted value whose content contains a `#`', () => {
    const doc = '---\ntitle: "a # b"   # c\n---\nbody\n';
    expect(setFrontmatterField(doc, 'title', 'x')).toBe('---\ntitle: x   # c\n---\nbody\n');
  });

  it('appends the field at the end of the frontmatter when absent', () => {
    const doc = '---\nid: a\n---\nbody\n';
    expect(setFrontmatterField(doc, 'rejection_reason', 'why')).toBe('---\nid: a\nrejection_reason: why\n---\nbody\n');
  });

  it('throws on a document without a frontmatter block', () => {
    expect(() => setFrontmatterField('no frontmatter', 'status', 'x')).toThrow('no frontmatter block');
  });

  it("(b) CRLF: keeps the edited line's CRLF ending, and appends with CRLF", () => {
    const doc = '---\r\nid: a\r\nstatus: draft   # c\r\n---\r\nbody\r\n';
    expect(setFrontmatterField(doc, 'status', 'pending')).toBe('---\r\nid: a\r\nstatus: pending   # c\r\n---\r\nbody\r\n');
    expect(setFrontmatterField(doc, 'rejection_reason', 'why')).toBe('---\r\nid: a\r\nstatus: draft   # c\r\nrejection_reason: why\r\n---\r\nbody\r\n');
  });

  it('(c) a plain value with an unspaced `#` (`dr#aft`) is matched and replaced, not duplicated', () => {
    const doc = '---\nid: a\nstatus: dr#aft\n---\nbody\n';
    const out = setFrontmatterField(doc, 'status', 'pending');
    expect(out).toBe('---\nid: a\nstatus: pending\n---\nbody\n');
    expect(parsed(out).status).toBe('pending');
  });

  it('(d) replaces a multi-line plain value together with its continuation lines', () => {
    const doc = '---\ntitle: first line\n  second line\n\n  third line\ntags: []\n---\nbody\n';
    const out = setFrontmatterField(doc, 'title', 'one');
    expect(out).toBe('---\ntitle: one\ntags: []\n---\nbody\n');
    expect(parsed(out)).toEqual({ title: 'one', tags: [] });
  });

  it('(d) replaces a multi-line double-quoted value up to its closing quote', () => {
    const doc = '---\ntitle: "first\n  still: title # not a comment\n  end"   # c\ntags: []\n---\nbody\n';
    const out = setFrontmatterField(doc, 'title', 'one');
    expect(out).toBe('---\ntitle: one\ntags: []\n---\nbody\n');
    expect(parsed(out)).toEqual({ title: 'one', tags: [] });
  });

  it('(a)/(d) replaces a `|` block scalar containing a blank line as a whole', () => {
    const doc = '---\nrejection_reason: |\n  First.\n\n  Second.\nstatus: draft\n---\nbody\n';
    const out = setFrontmatterField(doc, 'rejection_reason', 'short');
    expect(out).toBe('---\nrejection_reason: short\nstatus: draft\n---\nbody\n');
    expect(parsed(out)).toEqual({ rejection_reason: 'short', status: 'draft' });
  });

  it('writes an arbitrary string YAML-safely: quotes, colons, `#`, newlines, spaces, YAML-typed words round-trip exactly', () => {
    const doc = '---\nid: a\nstatus: draft\n---\nbody\n';
    for (const value of [
      'He said "no": fix it # now',
      'line one\nline two\n\nline four',
      "it's: a 'quote'",
      '  padded  ',
      'true',
      '123',
      '- dash',
      '',
      'back\\slash and tab\there',
    ]) {
      const out = setFrontmatterField(doc, 'rejection_reason', value);
      expect(parsed(out)).toEqual({ id: 'a', status: 'draft', rejection_reason: value });
    }
  });

  it('keeps a state-machine identifier plain (no quotes) so a status edit is a one-token diff', () => {
    const doc = '---\nstatus: draft\n---\n';
    expect(setFrontmatterField(doc, 'status', 'in-review')).toBe('---\nstatus: in-review\n---\n');
  });
});

describe('removeFrontmatterField', () => {
  it('removes a top-level key line and leaves every other byte intact', () => {
    expect(removeFrontmatterField(DOC, 'rejection_reason')).toBe(DOC.replace('rejection_reason: "needs tests"\n', ''));
  });

  it('removes the indented lines of a nested block value too', () => {
    const doc = '---\nid: a\nrejection_reason:\n  - line one\n  - line two\ntags: []\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\nid: a\ntags: []\n---\nbody\n');
  });

  it('is a no-op (same string) when the key is absent', () => {
    const doc = '---\nid: a\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe(doc);
  });

  it('removes the last frontmatter line cleanly', () => {
    const doc = '---\nid: a\nrejection_reason: x\n---\nbody\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\nid: a\n---\nbody\n');
  });

  it.each(['|', '>', '|-', '>+', '|2'])(
    '(a) removes a `%s` block scalar with a blank line as a whole — nothing leaks into the preceding key',
    (indicator) => {
      const doc = `---\nstatus: in-review\nrejection_reason: ${indicator}\n  First paragraph.\n\n  Second paragraph.\ntags: []\n---\nbody\n`;
      const out = removeFrontmatterField(doc, 'rejection_reason');
      expect(out).toBe('---\nstatus: in-review\ntags: []\n---\nbody\n');
      expect(parsed(out)).toEqual({ status: 'in-review', tags: [] });
    },
  );

  it('(a) a block scalar that is the LAST entry, with a blank line inside, is removed as a whole', () => {
    const doc = '---\nstatus: in-review\nrejection_reason: >\n  First.\n\n  Second.\n---\nbody\n';
    const out = removeFrontmatterField(doc, 'rejection_reason');
    expect(out).toBe('---\nstatus: in-review\n---\nbody\n');
    expect(parsed(out)).toEqual({ status: 'in-review' });
  });

  it('(a) block-scalar content lines that start with `#` are content, removed with it', () => {
    const doc = '---\nrejection_reason: |\n  # heading inside the text\n  body\nstatus: draft\n---\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\nstatus: draft\n---\n');
  });

  it('(b) CRLF: removes the entry and keeps CRLF on every remaining line', () => {
    const doc = '---\r\nstatus: draft\r\nrejection_reason: |\r\n  a\r\n\r\n  b\r\ntags: []\r\n---\r\nbody\r\n';
    const out = removeFrontmatterField(doc, 'rejection_reason');
    expect(out).toBe('---\r\nstatus: draft\r\ntags: []\r\n---\r\nbody\r\n');
    expect(parsed(out)).toEqual({ status: 'draft', tags: [] });
  });

  it('(e) an indented comment line after a plain value belongs to the mapping, not the value — kept', () => {
    const doc = '---\nrejection_reason: plain reason\n  # note: the tags below are generated\ntags: []\n---\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\n  # note: the tags below are generated\ntags: []\n---\n');
  });

  it("(e) a comment indented LESS than a block scalar's content is not content — kept", () => {
    const doc = '---\nrejection_reason: |\n    text\n\n  # parent comment\ntags: []\n---\n';
    const out = removeFrontmatterField(doc, 'rejection_reason');
    expect(out).toBe('---\n\n  # parent comment\ntags: []\n---\n');
    expect(parsed(out)).toEqual({ tags: [] });
  });

  it('(e) blank lines after a removed value stay, so the spacing before the next key is untouched', () => {
    const doc = '---\nrejection_reason: x\n  y\n\ntags: []\n---\n';
    expect(removeFrontmatterField(doc, 'rejection_reason')).toBe('---\n\ntags: []\n---\n');
  });
});

describe('verifyFrontmatterEdit — the post-condition checked before any transition write', () => {
  const before = '---\nid: a\ntitle: "T"\nstatus: draft\nrejection_reason: "x"\n---\nbody\n';

  it('passes when the expected fields hold and every other field is unchanged', () => {
    const after = '---\nid: a\ntitle: "T"\nstatus: pending\n---\nbody\n';
    expect(verifyFrontmatterEdit(before, after, { status: 'pending', rejection_reason: undefined })).toEqual([]);
  });

  it('reports a status that is not the target (the rejection repro: a block scalar leaking into status)', () => {
    const after = '---\nid: a\ntitle: "T"\nstatus: pending\n  Second paragraph.\n---\nbody\n';
    expect(verifyFrontmatterEdit(before, after, { status: 'pending', rejection_reason: undefined })).toEqual([
      "field 'status' is \"pending Second paragraph.\", expected \"pending\"",
    ]);
  });

  it('reports a field that should be absent but is present', () => {
    expect(verifyFrontmatterEdit(before, before.replace('draft', 'pending'), { status: 'pending', rejection_reason: undefined })).toEqual([
      "field 'rejection_reason' is still present, expected it removed",
    ]);
  });

  it('reports any OTHER field whose parsed value changed', () => {
    const after = '---\nid: a\ntitle: "U"\nstatus: pending\n---\nbody\n';
    expect(verifyFrontmatterEdit(before, after, { status: 'pending', rejection_reason: undefined })).toEqual([
      "field 'title' changed although this operation does not own it",
    ]);
  });

  it('reports rendered frontmatter that no longer parses', () => {
    const after = '---\nid: a\ntitle: "T\nstatus: pending\n---\nbody\n';
    const problems = verifyFrontmatterEdit(before, after, { status: 'pending' });
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/^rendered frontmatter is not valid YAML: /);
  });

  it('reports a missing frontmatter block', () => {
    expect(verifyFrontmatterEdit(before, 'no frontmatter', { status: 'pending' })).toEqual(['rendered document has no frontmatter block']);
  });
});
