/**
 * `renderRejectDocument` (task-047-memory-reject) — the pure document edit behind
 * `wingfoil memory reject` (P1.8), the counterpart of `./submit.ts`'s `renderSubmitDocument`.
 *
 * `spec-010-memory-frontmatter-schema`'s field-write ownership table makes `memory.reject` the one
 * transition verb that writes TWO fields: `status` (the type's `gates.<state>.reject` target) and
 * `rejection_reason` (the `--reason` text, verbatim). Everything else in the document — the other
 * frontmatter entries, their inline comments, and the whole body — must survive byte for byte, and
 * the result must parse back to exactly the reason the user typed whatever characters it contains.
 */
import { load } from 'js-yaml';

import { renderRejectDocument } from '../../src/memory/reject';
import { splitFrontmatter } from '../../src/storage';

const DOC = `---
id: "task-101"         # auto-generated by wingfoil
type: task
title: "Ship it"       # REQUIRED
status: pending        # auto-set by wingfoil
tags: []
---

## Description

rejection_reason: this body line is not frontmatter
`;

/** Parse a document's frontmatter the way every reader of Memory documents does. */
function parsed(content: string): Record<string, unknown> {
  return load(splitFrontmatter(content).frontmatter ?? '') as Record<string, unknown>;
}

describe('renderRejectDocument', () => {
  it('sets `status` to the target and appends `rejection_reason`, keeping every other byte', () => {
    const out = renderRejectDocument(DOC, 'draft', 'tests missing');
    expect(out).toBe(DOC.replace('status: pending ', 'status: draft ').replace('tags: []', 'tags: []\nrejection_reason: "tests missing"'));
    expect(parsed(out)).toEqual({ id: 'task-101', type: 'task', title: 'Ship it', status: 'draft', tags: [], rejection_reason: 'tests missing' });
  });

  it('replaces an existing `rejection_reason` in place rather than adding a second key', () => {
    const once = renderRejectDocument(DOC, 'draft', 'first');
    const twice = renderRejectDocument(once, 'draft', 'second');
    expect(twice.match(/^rejection_reason:/gm)).toHaveLength(1);
    expect(parsed(twice).rejection_reason).toBe('second');
  });

  it('never touches a `status:`/`rejection_reason:` line in the BODY (column-0 keys in frontmatter only)', () => {
    expect(renderRejectDocument(DOC, 'draft', 'x')).toContain('rejection_reason: this body line is not frontmatter');
  });

  it.each([
    ['a colon and a hash', 'see: docs/x.md#anchor'],
    ['quotes', 'the "tests" are \'missing\''],
    ['a leading dash (a YAML sequence indicator)', '- rewrite the tests'],
    ['a YAML-typed word', 'no'],
    ['a newline', 'first line\nsecond line'],
    ['leading and trailing whitespace', '   padded   '],
    ['unicode', 'ünïcode — em dash, 日本語'],
    ['a lone backslash', 'escape \\ this'],
    ['an empty string', ''],
  ])('serializes a reason containing %s so it parses back verbatim', (_label, reason) => {
    expect(parsed(renderRejectDocument(DOC, 'draft', reason)).rejection_reason).toBe(reason);
  });
});
