/**
 * P1.6 (US-3-09) — `wingfoil memory submit` core-op fit criteria, per
 * `docs/02_requirements/02_bdd/features/p1-memory/P1.6-memory-submit.feature` (all three scenarios),
 * `dl-032-illegal-transition-message-contract` (the pinned illegal-transition message, exit `1`),
 * `spec-010-memory-frontmatter-schema` (submit sets `status`, removes `rejection_reason`; title and
 * every `template.frontmatter.required` field must be non-empty once `status` leaves `draft`),
 * `spec-004-mcp-surface-contract` §4.3 (one commit, subject `wf({type}): {verb} {id}`),
 * `spec-008-cli-grammar` §5/§7 (bare `<id>`; not found → `1`; missing argument → `2`) and
 * REQ-SEC-01 (git-identity pre-flight).
 *
 * Exercises the REAL, registered `CORE_MODULES` `memory.memorySubmit` operation — the exact `CoreFn`
 * the CLI command and the MCP Tool dispatch to. Every write lands in a THROWAWAY temp git repo.
 *
 * The `task` fixture type carries the REAL `task` state machine from `docs/self/.wingfoil/memory.yaml`
 * (not the default machine), because P1.6's pinned message must hold against the machine this project
 * actually runs — there `approved` is a `waiting` state whose forward edge is `done`, not `pending`.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { CORE_MODULES } from '../../src/core';
import type { CoreFn } from '../../src/core/registry';
import { exitCodeForResult, exitCodeForThrow } from '../../src/core/exit-code';
import { UsageError } from '../../src/core/usage-error';
import { commitAll, makeTempGitRepo, removeTempDir, writeFixtureFile } from '../storage/helpers/git-fixture';

const MEMORY_YAML = `version: 1
defaults:
  states:
    sequence: [draft, pending, approved]
    gates:
      pending: { reject: draft }
types:
  task:
    path: "docs/memory/{release}/{id}.md"
    template:
      file: "memory/templates/task.md"
      frontmatter:
        required: [title, release]
    states:
      sequence: [draft, pending, backlog, in-progress, in-review, approved, done]
      gates:
        pending: { reject: draft }
        in-review: { reject: in-progress }
      waiting: [backlog, approved]
  note:
    path: "docs/memory/note/{id}.md"
`;

interface SubmitValue {
  readonly id: string;
  readonly path: string;
  readonly from: string;
  readonly to: string;
}

/** The real, registered `memory.memorySubmit` `CoreFn` — fails loudly if a future change un-registers it. */
function memorySubmitFn(): CoreFn<unknown, SubmitValue> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memorySubmit;
  if (!operation) throw new Error('fixture bug: "memorySubmit" operation not registered on the memory module');
  return operation.fn as CoreFn<unknown, SubmitValue>;
}

function memoryHistoryFn(): CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null }[] }> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memoryHistory;
  if (!operation) throw new Error('fixture bug: "memoryHistory" operation not registered');
  return operation.fn as CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null }[] }>;
}

function gitOut(repo: string, args: string[]): string {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf-8' }).trim();
}
const head = (repo: string): string => gitOut(repo, ['rev-parse', 'HEAD']);

function taskDoc(fields: { id: string; status: string; title?: string; release?: string; extra?: string }): string {
  return `---
id: "${fields.id}"          # auto-generated by wingfoil
type: task
title: "${fields.title ?? 'A task'}"   # REQUIRED
status: ${fields.status}          # auto-set by wingfoil
release: "${fields.release ?? 'v0.2'}"   # REQUIRED
${fields.extra ?? ''}tmpl_version: 260703
---

## Description

Real content.
`;
}

describe('CORE_MODULES memory.memorySubmit — P1.6 fit criteria', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'draft' }));
    writeFixtureFile(repo, 'docs/memory/v0.2/task-200.md', taskDoc({ id: 'task-200', status: 'approved' }));
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  it('P1.6 sc.1: moves a draft to `status: pending`, in exactly one scoped `wf(task): submit task-101` commit, exit 0', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101', positionals: ['task-101'] });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(exitCodeForResult(result)).toBe(0);
    expect(result.value).toEqual({ id: 'task-101', path: 'docs/memory/v0.2/task-101.md', from: 'draft', to: 'pending' });

    const content = readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8');
    // Only the status value changed; its inline comment and every other byte survive.
    expect(content).toBe(taskDoc({ id: 'task-101', status: 'draft' }).replace('status: draft', 'status: pending'));

    // The transition is recorded in git: one new commit, subject only, scoped to the one file.
    expect(gitOut(repo, ['rev-list', '--count', `${before}..HEAD`])).toBe('1');
    expect(result.commit).toEqual({ sha: head(repo), message: 'wf(task): submit task-101' });
    expect(gitOut(repo, ['log', '-1', '--format=%B'])).toBe('wf(task): submit task-101');
    expect(gitOut(repo, ['show', '--name-only', '--format=', 'HEAD'])).toBe('docs/memory/v0.2/task-101.md');
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('commits the content the author wrote before submitting (submit = fill content + move state, one commit)', async () => {
    const path = join(repo, 'docs/memory/v0.2/task-101.md');
    writeFileSync(path, readFileSync(path, 'utf-8').replace('Real content.', 'Real content, now finished.'));
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101' });
    expect(result.ok).toBe(true);
    expect(gitOut(repo, ['show', 'HEAD:docs/memory/v0.2/task-101.md'])).toContain('Real content, now finished.');
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('P1.6 sc.2: an illegal transition (approved -> pending) leaves the state unchanged and exits 1 with the pinned message', async () => {
    const before = head(repo);
    const original = readFileSync(join(repo, 'docs/memory/v0.2/task-200.md'), 'utf-8');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-200' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('INVALID_TRANSITION');
    expect(result.error.message).toBe("illegal transition approved -> pending for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-200.md'), 'utf-8')).toBe(original);
    expect(head(repo)).toBe(before);
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('P1.6 sc.3: a non-existent document exits 1 with `document not found: task-999`', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-999' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('NOT_FOUND');
    expect(result.error.message).toBe('document not found: task-999');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });

  it('a missing or blank `<id>` is a usage error (exit 2) — spec-008 §5/§7', async () => {
    for (const positional of [undefined, '  ']) {
      await expect(memorySubmitFn()({ root: repo, positional })).rejects.toBeInstanceOf(UsageError);
      try {
        await memorySubmitFn()({ root: repo, positional });
      } catch (error) {
        expect(exitCodeForThrow(error)).toEqual({ reason: 'missing required argument: memory submit <id>', exitCode: 2 });
      }
    }
  });

  it('spec-010: an empty required field refuses the submit (exit 1), naming every missing field in declared order, writing nothing', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-102.md', taskDoc({ id: 'task-102', status: 'draft', title: '', release: '' }));
    commitAll(repo, 'seed 102');
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-102' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe('missing required field on submit: title, release');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-102.md'), 'utf-8')).toContain('status: draft');
  });

  it('spec-010: a resubmit after a reject removes `rejection_reason` from the frontmatter', async () => {
    writeFixtureFile(
      repo,
      'docs/memory/v0.2/task-103.md',
      taskDoc({ id: 'task-103', status: 'draft', extra: 'rejection_reason: "add the missing tests"\n' }),
    );
    commitAll(repo, 'seed 103');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-103' });
    expect(result.ok).toBe(true);
    const content = readFileSync(join(repo, 'docs/memory/v0.2/task-103.md'), 'utf-8');
    expect(content).not.toContain('rejection_reason');
    expect(content).toBe(taskDoc({ id: 'task-103', status: 'pending' }));
  });

  it('drives every plain forward edge, not only draft: in-progress -> in-review (spec-001)', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-104.md', taskDoc({ id: 'task-104', status: 'in-progress' }));
    commitAll(repo, 'seed 104');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-104' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('in-review');
    expect(result.commit?.message).toBe('wf(task): submit task-104');
  });

  it('a type without its own machine falls back to `defaults.states` (REQ-STATE-08)', async () => {
    writeFixtureFile(repo, 'docs/memory/note/note-1.md', '---\nid: note-1\ntype: note\ntitle: "N"\nstatus: draft\n---\nbody\n');
    commitAll(repo, 'seed note');
    const result = await memorySubmitFn()({ root: repo, positional: 'note-1' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('pending');
    expect(result.commit?.message).toBe('wf(note): submit note-1');
  });

  it('a `status` that is not a state of the type exits 1 with the task-036 message, writing nothing', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-105.md', taskDoc({ id: 'task-105', status: 'shipped' }));
    commitAll(repo, 'seed 105');
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-105' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe("invalid state 'shipped' for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });

  it('a document whose `type` is not registered exits 1 with the `memory add` unknown-type message', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/odd.md', '---\nid: odd-1\ntype: unicorn\ntitle: "U"\nstatus: draft\n---\n');
    commitAll(repo, 'seed odd');
    const result = await memorySubmitFn()({ root: repo, positional: 'odd-1' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('NOT_FOUND');
    expect(result.error.message).toBe("unknown memory type 'unicorn' (not defined in memory.yaml)");
  });

  it('`memory history` reads the submit back as operation `submit`, draft -> pending (P1.10 round-trip)', async () => {
    await memorySubmitFn()({ root: repo, positional: 'task-101' });
    const history = await memoryHistoryFn()({ root: repo, positional: 'task-101' });
    expect(history.ok).toBe(true);
    if (!history.ok) return;
    const last = history.value.entries[history.value.entries.length - 1];
    expect(last).toMatchObject({ operation: 'submit', from: 'draft', to: 'pending' });
  });
});

describe('CORE_MODULES memory.memorySubmit — configuration without any state machine', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    // The shape `wingfoil init` scaffolds today: types with no `states:` and no `defaults:` block.
    writeFixtureFile(repo, '.wingfoil/memory.yaml', 'version: 1\ntypes:\n  task:\n    path: docs/memory/task/{id}.md\n');
    writeFixtureFile(repo, 'docs/memory/task/task-1.md', '---\nid: task-1\ntype: task\ntitle: "T"\nstatus: draft\n---\n');
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  it('is a VALIDATION error (exit 1) naming REQ-STATE-08, never an escaped throw', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-1' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toContain('REQ-STATE-08');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });
});

describe('CORE_MODULES memory.memorySubmit — REQ-SEC-01 git-identity pre-flight (no configured identity)', () => {
  const ISOLATION_KEYS = ['GIT_CONFIG_GLOBAL', 'GIT_CONFIG_SYSTEM', 'GIT_CONFIG_NOSYSTEM'] as const;
  const saved: Record<string, string | undefined> = {};
  let repo: string;

  beforeEach(() => {
    repo = mkdtempSync(join(tmpdir(), 'wf-memsubmit-noid-'));
    execFileSync('git', ['-C', repo, 'init', '-q', '--initial-branch=main'], { encoding: 'utf-8' });
    const emptyConfig = join(repo, 'empty.gitconfig');
    writeFileSync(emptyConfig, '');
    for (const key of ISOLATION_KEYS) saved[key] = process.env[key];
    process.env.GIT_CONFIG_GLOBAL = emptyConfig;
    process.env.GIT_CONFIG_SYSTEM = emptyConfig;
    process.env.GIT_CONFIG_NOSYSTEM = '1';
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'draft' }));
  });

  afterEach(() => {
    for (const key of ISOLATION_KEYS) {
      if (saved[key] === undefined) delete process.env[key];
      else process.env[key] = saved[key];
    }
    rmSync(repo, { recursive: true, force: true });
  });

  it('refuses with the exact REQ-SEC-01 message (exit 1), writing nothing', async () => {
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('git identity not configured (user.name/user.email)');
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toContain('status: draft');
  });
});
